name: Deploy fluentai

on:
  push:
    branches:
      - main # The branch that triggers the deployment

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install NX
      run: npm install -g nx

    - name: Install dependencies
      run: npm ci

    - name: Build NX project
      run: nx build fluentai

    - name: Install rsync
      run: sudo apt-get -y install rsync

    - name: Copy build to server
      env:
        DEPLOY_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dist/apps/fluentai/ theron@194.13.83.192:/home/theron/fluentAI/build/public

    - name: Run build script on server
      run: ssh -o StrictHostKeyChecking=no theron@194.13.83.192 'bash /home/theron/fluentAI/build.sh'
