name: Deploy fluentai

on:
  push:
    branches:
      - build-workflow-main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate hash and save to file
      id: generate_hash
      run: |
        mkdir -p ./dist/apps/fluentai/
        node getHash.js > hash.txt
        echo "hash=$(cat hash.txt)" >> $GITHUB_ENV

    - name: Fetch previous hash from server
      id: fetch_previous_hash
      env:
        DEPLOY_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "prev_hash=$(ssh -o StrictHostKeyChecking=no theron@194.13.83.192 'cat /home/theron/fluentAI/staging/hash.txt || echo')" >> $GITHUB_ENV

    - name: Compare hashes
      id: compare_hashes
      run: |
        echo "Current hash: ${{ env.hash }}"
        echo "Previous hash: ${{ env.prev_hash }}"
        if [ "${{ env.hash }}" = "${{ env.prev_hash }}" ]; then
          echo "match=true" >> $GITHUB_ENV
        else
          echo "match=false" >> $GITHUB_ENV
        fi

    - name: Install NX
      if: env.match == 'false'
      run: npm install -g nx

    - name: Install dependencies
      if: env.match == 'false'
      run: npm ci

    - name: Build NX project
      if: env.match == 'false'
      run: nx build fluentai

    - name: Install rsync
      if: env.match == 'false'
      run: sudo apt-get -y install rsync

    - name: Copy build to server
      if: env.match == 'false'
      env:
        DEPLOY_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dist/apps/fluentai/ theron@194.13.83.192:/home/theron/fluentAI/build/public

    - name: Hash matches, using cached build
      if: env.match == 'true'
      run: ssh -o StrictHostKeyChecking=no theron@194.13.83.192 'cp -r /home/theron/fluentAI/staging/build/public/* /home/theron/fluentAI/build/public/'

    - name: Run build script on server
      run: ssh -o StrictHostKeyChecking=no theron@194.13.83.192 'bash /home/theron/fluentAI/build.sh'
